document.write('<link rel="stylesheet" href="style.css">')
document.write('<table><tr>')
document.write('<td>Up: <a href="index.html">go back to the main page</a></td> <td>|</td>')
document.write('<td>Github: <a href="https://github.com/dsp-box/ccROJ">go to the project page</a></td>')
document.write('</tr></table>')
document.write('<center>')
document.write('  <span class="title">ccROJ</span><br>')
document.write('  <br><b>Time-Frequency C++ Framework</b><br>')
document.write('  reference manual (version 0-43)')
document.write('</center>')